import { createFileRoute, Link } from "@tanstack/react-router";
import { Swords } from "lucide-react";
import { categoryIcons } from "@/components/category-sidebar";
import { GameCard } from "@/components/game-card";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { categories } from "@/data/games";
import { useGames } from "@/hooks/use-games";
export const Route = createFileRoute("/categorias")({ ssr:false, component: CategoriesPage });
function CategoriesPage() { const games=useGames(); return <div className="min-h-screen"><SiteHeader/><main className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><nav className="text-xs text-muted-foreground"><Link to="/">Início</Link> / Categorias</nav><h1 className="mt-2 font-display text-3xl font-extrabold uppercase">Categorias</h1><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{categories.map(cat=>{const Icon=categoryIcons[cat.icon]??Swords;const list=games.filter(g=>g.categories.includes(cat.slug));return <Link key={cat.slug} to="/jogos" search={{cat:cat.slug,q:undefined}} className="rounded-xl border border-border/70 bg-card p-5 hover:border-primary/60"><span className="grid size-11 place-items-center rounded-lg bg-surface-2 text-primary"><Icon className="size-5"/></span><h2 className="mt-3 font-display text-lg font-bold">{cat.name}</h2><p className="mt-1 text-xs text-muted-foreground">{cat.description}</p><p className="mt-3 text-xs font-semibold uppercase tracking-widest text-primary">{list.length} jogos</p></Link>})}</div><div className="mt-12 space-y-10">{categories.map(cat=>{const list=games.filter(g=>g.categories.includes(cat.slug)).slice(0,6);if(!list.length)return null;return <section key={cat.slug}><h2 className="mb-4 font-display text-xl font-extrabold uppercase">{cat.name}</h2><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5 xl:grid-cols-6">{list.map(g=><GameCard key={g.id} game={g}/>)}</div></section>})}</div></main><SiteFooter/></div>; }
