import { createFileRoute, Link } from "@tanstack/react-router";
import { Star, TrendingUp } from "lucide-react";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { formatPlays } from "@/data/games";
import { useGames } from "@/hooks/use-games";
const SITE_URL="https://gamehub-portal.pages.dev";
export const Route=createFileRoute("/mais-jogados")({component:MostPlayedPage,head:()=>{const title="Mais Jogados — Jogos Populares Online | GameHub";const description="Veja os jogos mais jogados do GameHub, organizados pelas partidas registradas. Descubra os jogos populares e jogue online grátis.";const breadcrumb={"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Início",item:SITE_URL+"/"},{"@type":"ListItem",position:2,name:"Mais Jogados",item:SITE_URL+"/mais-jogados"}]};return{meta:[{title},{name:"description",content:description},{name:"robots",content:"index, follow, max-image-preview:large"},{property:"og:title",content:title},{property:"og:description",content:description},{property:"og:type",content:"website"},{property:"og:url",content:SITE_URL+"/mais-jogados"},{property:"og:site_name",content:"GameHub"},{name:"twitter:card",content:"summary_large_image"},{name:"twitter:title",content:title},{name:"twitter:description",content:description}],links:[{rel:"canonical",href:SITE_URL+"/mais-jogados"},{rel:"alternate",hrefLang:"pt-BR",href:SITE_URL+"/mais-jogados"}],scripts:[{type:"application/ld+json",children:JSON.stringify(breadcrumb)}]};}});
function MostPlayedPage(){const ranking=[...useGames()].sort((a,b)=>b.plays-a.plays);return <div className="min-h-screen"><SiteHeader/><main className="mx-auto max-w-5xl px-4 py-8 sm:px-6"><nav className="text-xs text-muted-foreground"><Link to="/" className="hover:text-primary">Início</Link><span className="mx-2">/</span>Mais Jogados</nav><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 className="flex items-center gap-2 font-display text-3xl font-extrabold uppercase sm:text-4xl"><TrendingUp className="size-7 text-primary"/> Mais Jogados</h1><p className="mt-1 text-sm text-muted-foreground">Os jogos com mais partidas registradas no GameHub.</p></div><Link to="/ranking" className="inline-flex items-center rounded-lg border border-border bg-surface px-4 py-2 text-xs font-bold transition-colors hover:border-primary/60 hover:text-primary">Ranking de jogadores</Link></div><ol className="mt-6 grid gap-2">{ranking.map((game,i)=><li key={game.id}><Link to="/jogo/$slug" params={{slug:game.slug}} className="group grid grid-cols-[auto_auto_minmax(0,1fr)_auto] items-center gap-3 rounded-xl border border-border/70 bg-card p-3 transition-all hover:-translate-y-0.5 hover:border-primary/50 hover:shadow-card"><span className="w-8 text-center text-2xl font-extrabold text-muted-foreground group-hover:text-primary">{i+1}</span><img src={game.cover} alt="" className="size-16 rounded-lg object-cover"/><span className="min-w-0"><span className="block truncate font-bold group-hover:text-primary">{game.title}</span><span className="block truncate text-xs text-muted-foreground">{game.genre}</span><span className="mt-1 flex items-center gap-1 text-xs text-gold"><Star className="size-3 fill-current"/>{game.rating.toFixed(1)}</span></span><span className="text-right text-sm font-bold">{formatPlays(game.plays)} <span className="block text-[10px] font-medium uppercase tracking-wider text-muted-foreground">partidas</span></span></Link></li>)}</ol></main><SiteFooter/></div>}
