import { createFileRoute } from "@tanstack/react-router";
import { Crown, Gamepad2, Trophy } from "lucide-react";
import { useEffect,useState } from "react";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { listLeaderboard,type LeaderboardEntry } from "@/lib/leaderboard";
export const Route=createFileRoute("/ranking")({ssr:false,head:()=>({meta:[{title:"Ranking — GameHub"}]}),component:RankingPage});
const time=(ms:number)=>{const m=Math.floor(ms/60000);return m<60?m+" min":Math.floor(m/60)+"h "+m%60+"min"};
function RankingPage(){const[e,setE]=useState<LeaderboardEntry[]>([]),[l,setL]=useState(true);
useEffect(()=>{void listLeaderboard(50).then(setE).catch(console.error).finally(()=>setL(false))},[]);
return <div className="min-h-screen"><SiteHeader/><main className="mx-auto max-w-5xl px-4 py-10 sm:px-6 sm:py-14"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="flex items-center gap-2 text-primary"><Trophy className="size-6"/><span className="text-xs font-bold uppercase tracking-[0.2em]">GameHub</span></div><h1 className="mt-2 font-display text-3xl font-extrabold uppercase sm:text-5xl">Ranking</h1><p className="mt-2 text-sm text-muted-foreground">100 pontos por jogo diferente + 1 ponto por minuto jogado.</p></div></div>
<section className="mt-8 overflow-hidden rounded-2xl border border-border bg-card shadow-card">{l?<div className="p-10 text-center text-sm text-muted-foreground">Carregando ranking...</div>:e.length===0?<div className="p-10 text-center"><Trophy className="mx-auto size-10 text-primary"/><p className="mt-3 font-bold">O ranking ainda está vazio.</p><p className="mt-1 text-sm text-muted-foreground">Jogue um jogo para entrar.</p></div>:<div className="divide-y divide-border/70">{e.map((x,i)=><div key={x.userId} className="flex items-center gap-3 p-4 sm:gap-5 sm:p-5"><div className="grid size-10 shrink-0 place-items-center rounded-xl bg-secondary font-display text-lg font-extrabold">{i<3?<Crown className="size-5 text-primary"/>:i+1}</div>{x.avatarUrl?<img src={x.avatarUrl} alt="" className="size-11 rounded-full border border-border object-cover"/>:<div className="grid size-11 place-items-center rounded-full bg-gradient-violet text-sm font-bold text-primary-foreground">{x.displayName.slice(0,2).toUpperCase()}</div>}<div className="min-w-0 flex-1"><p className="truncate font-bold">{x.displayName}</p><div className="mt-1 flex gap-3 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1"><Gamepad2 className="size-3.5"/>{x.gamesPlayed} jogos</span><span>{time(x.playTimeMs)} jogados</span></div></div><div className="text-right"><p className="font-display text-xl font-extrabold text-primary">{x.points.toLocaleString("pt-BR")}</p><p className="text-[10px] font-bold uppercase text-muted-foreground">pontos</p></div></div>)}</div>}</section></main><SiteFooter/></div>}