/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as DefinirSenhaRouteImport } from './routes/definir-senha'
import { Route as JogosRouteImport } from './routes/jogos'
import { Route as MaisJogadosRouteImport } from './routes/mais-jogados'
import { Route as NovosRouteImport } from './routes/novos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as AdminJogosRouteImport } from './routes/admin.jogos'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as JogoSlugRouteImport } from './routes/jogo.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const DefinirSenhaRoute = DefinirSenhaRouteImport.update({
  id: '/definir-senha',
  path: '/definir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const JogosRoute = JogosRouteImport.update({
  id: '/jogos',
  path: '/jogos',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisJogadosRoute = MaisJogadosRouteImport.update({
  id: '/mais-jogados',
  path: '/mais-jogados',
  getParentRoute: () => rootRouteImport,
} as any)
const NovosRoute = NovosRouteImport.update({
  id: '/novos',
  path: '/novos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJogosRoute = AdminJogosRouteImport.update({
  id: '/admin/jogos',
  path: '/admin/jogos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const JogoSlugRoute = JogoSlugRouteImport.update({
  id: '/jogo/$slug',
  path: '/jogo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/categorias': typeof CategoriasRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/jogos': typeof JogosRoute
  '/mais-jogados': typeof MaisJogadosRoute
  '/novos': typeof NovosRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/admin/jogos': typeof AdminJogosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/jogo/$slug': typeof JogoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/categorias': typeof CategoriasRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/jogos': typeof JogosRoute
  '/mais-jogados': typeof MaisJogadosRoute
  '/novos': typeof NovosRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/admin/jogos': typeof AdminJogosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/jogo/$slug': typeof JogoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/categorias': typeof CategoriasRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/jogos': typeof JogosRoute
  '/mais-jogados': typeof MaisJogadosRoute
  '/novos': typeof NovosRoute
  '/perfil': typeof PerfilRoute
  '/ranking': typeof RankingRoute
  '/admin/jogos': typeof AdminJogosRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/jogo/$slug': typeof JogoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/categorias'
    | '/definir-senha'
    | '/jogos'
    | '/mais-jogados'
    | '/novos'
    | '/perfil'
    | '/ranking'
    | '/admin/jogos'
    | '/auth/callback'
    | '/jogo/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/categorias'
    | '/definir-senha'
    | '/jogos'
    | '/mais-jogados'
    | '/novos'
    | '/perfil'
    | '/ranking'
    | '/admin/jogos'
    | '/auth/callback'
    | '/jogo/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/categorias'
    | '/definir-senha'
    | '/jogos'
    | '/mais-jogados'
    | '/novos'
    | '/perfil'
    | '/ranking'
    | '/admin/jogos'
    | '/auth/callback'
    | '/jogo/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  CategoriasRoute: typeof CategoriasRoute
  DefinirSenhaRoute: typeof DefinirSenhaRoute
  JogosRoute: typeof JogosRoute
  MaisJogadosRoute: typeof MaisJogadosRoute
  NovosRoute: typeof NovosRoute
  PerfilRoute: typeof PerfilRoute
  RankingRoute: typeof RankingRoute
  AdminJogosRoute: typeof AdminJogosRoute
  JogoSlugRoute: typeof JogoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definir-senha': {
      id: '/definir-senha'
      path: '/definir-senha'
      fullPath: '/definir-senha'
      preLoaderRoute: typeof DefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogos': {
      id: '/jogos'
      path: '/jogos'
      fullPath: '/jogos'
      preLoaderRoute: typeof JogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mais-jogados': {
      id: '/mais-jogados'
      path: '/mais-jogados'
      fullPath: '/mais-jogados'
      preLoaderRoute: typeof MaisJogadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novos': {
      id: '/novos'
      path: '/novos'
      fullPath: '/novos'
      preLoaderRoute: typeof NovosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/jogos': {
      id: '/admin/jogos'
      path: '/admin/jogos'
      fullPath: '/admin/jogos'
      preLoaderRoute: typeof AdminJogosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/jogo/$slug': {
      id: '/jogo/$slug'
      path: '/jogo/$slug'
      fullPath: '/jogo/$slug'
      preLoaderRoute: typeof JogoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  CategoriasRoute: CategoriasRoute,
  DefinirSenhaRoute: DefinirSenhaRoute,
  JogosRoute: JogosRoute,
  MaisJogadosRoute: MaisJogadosRoute,
  NovosRoute: NovosRoute,
  PerfilRoute: PerfilRoute,
  RankingRoute: RankingRoute,
  AdminJogosRoute: AdminJogosRoute,
  JogoSlugRoute: JogoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
